### ISSUE TITLE
Bug in AC button in the calculator

### ISSUE THREAD

**Issue by palsiddharth091** [Emilance/Javascript-Calculator-App#11]
When the AC button in the calculator is clicked. Only the arithmetical expression is being deleted. But the result is not being deleted. In real calculator AC stands for all clear which means the mathematical expression as well as the result of it must be deleted i.e 0. @Emilance I would like to work on this issue and debug this.

**Comment by Emilance** [comment]
go ahead @palsiddharth091,  you can start working on this

**Comment by eddejayaklu** [comment]
could i even debug and fix? @Emilance @palsiddharth091
