### ISSUE TITLE
🐛 Operators precedence error on final evaluation

### ISSUE THREAD

**Issue by wendirad** [Emilance/Javascript-Calculator-App#23]
Cc: @Emilance 

Hi, @Emilance

### The final answer on multiple operators shows wrong answer
When user write an expressions with multiple operators, which have different precedence the current app is evaluting the result from right left with out considering the operators precedence.

### To Reproduce
1. Go to https://emmycalculatorapp.netlify.app/
2. type the following expression `1/2 - 1/5`
3. press `=`
4. Check error, return `-0.1` actual answer `0.3`

### Expected Behavior
The Calculator suppose to evaluate the expression based on their precedence instead of a given order.

### Tasks
- [x] Investigate
- [x] Fix

### Suggested Approach
- Convert a given expression into [Postfix Expression](https://www.tutorialspoint.com/Convert-Infix-to-Postfix-Expression) and evaluate postfix expression.

### Screenshots
![Screenshot_20221014-114432.png](https://user-images.githubusercontent.com/53967346/195809064-a12452de-fb9b-4e3d-9a02-88b88ce91eab.png)

> NOTE: I'm looking forward to implement this feature, so assign the issue to me.

Thanks!

**Comment by Emilance** [comment]
@wendirad  thanks for raising this issue, I'll assign it to you now, go ahead
