### ISSUE TITLE
Want to create the calculator scientific 

### ISSUE THREAD

**Issue by noobtdbs** [Emilance/Javascript-Calculator-App#24]
Add trigonometric sections , logarithmic sections etc...

**Comment by Emilance** [comment]
Nice issue @noobtdbs , should I assign this to you?

**Comment by ShreejaMehta** [comment]
Hello! 
I would like to work on this issue...
Can you assign it to me?

**Comment by VIJAYKATARI23** [comment]
Could you please assign this issue for me with hacktoberfest label?

**Comment by Emilance** [comment]
okay @ShreejaMehta, go ahead,  I'm assigning this to you
