### ISSUE TITLE
Adding dark/light mode preference.

### ISSUE THREAD

**Issue by DarkFalc0n** [Emilance/Javascript-Calculator-App#26]
Currently, the calculator's dark/light mode gets reset upon refreshing, I want to save the user preference for future so that the website loads in the chosen theme each time.

**Comment by DarkFalc0n** [comment]
@DKendle I am a contributor, and hence I cannot assign you.

**Comment by Emilance** [comment]
Nice issue @DarkFalc0n,  should I assign this to you or @DKendle  ?

**Comment by DarkFalc0n** [comment]
@Emilance Well, I would like to work on this issue, and since I created it, it is my request to assign this to me. I will pass this issue on to the next person if I am unable to satisfactorily solve this.

**Comment by krishnabiradar310802** [comment]
@DarkFalc0n Can i work on this issue?

**Comment by DarkFalc0n** [comment]
@Emilance Can you assign this issue to me?

**Comment by Emilance** [comment]
Oh yeah I will , go ahead @DarkFalc0n
