### ISSUE TITLE
Want to Add Re-sum Feature

### ISSUE THREAD

**Issue by fadzikri** [Emilance/Javascript-Calculator-App#29]
Hello, i'm here want to add re-sum feature. Instead of user just can click result one time, i want user can do re-sum. I mean, like this.

2 x 4 = 8
8 x 4 = 32
32 x 4 = 128

I know some of calculator can't do that, but the other do.

**Comment by Emilance** [comment]
Okay @fadzikri ,  that will be a nice feature, go ahead
