### ISSUE TITLE
Create animated background

### ISSUE THREAD

**Issue by Mahak008** [Emilance/Javascript-Calculator-App#4]

**Comment by Emilance** [comment]
Go ahead  @Mahak008,  you can start  working on it, let me know if you need  help in anyways

**Comment by Emilance** [comment]
Okay @Mahak008 , should I assign this to you ?

**Comment by Mahak008** [comment]
> Okay @Mahak008 , should I assign this to you ?

Yes, please assign it to me

**Comment by Mahak008** [comment]
May I please know why this pr is been closed @Emilance
