### ISSUE TITLE
Fixing display of numbers

### ISSUE THREAD

**Issue by YuriCodes** [Emilance/Javascript-Calculator-App#42]
It is not centered currently which makes it look bad and not very friendly. 

I can work on this if you'd like. 

**This would be the end result:** 
<img width="1340" alt="Screen Shot 2022-10-15 at 10 52 31 AM" src="https://user-images.githubusercontent.com/80093500/195992889-466777fc-5f98-42eb-a752-e23004033876.png">

How it currently looks: 
<img width="1340" alt="Screen Shot 2022-10-15 at 10 51 03 AM" src="https://user-images.githubusercontent.com/80093500/195992842-4f2e6b91-21c2-4ecb-a4a3-dcfb580c47aa.png">

**Comment by Emilance** [comment]
😲😲wow!, I am very happy and deeply  honored to have  Yuri raising issue in my repo, thanks a lot,
 I appreciate this
