### ISSUE TITLE
Need  to  position the calculator at  the center of the page

### ISSUE THREAD

**Issue by Emilance** [Emilance/Javascript-Calculator-App#68]
The calculator should be centered at the middle of the page

![calc](https://user-images.githubusercontent.com/100171190/210281705-4ba71c4a-6786-4874-b799-1bfde4a61c4c.PNG)

**Comment by Rishav1707** [comment]
Shall I work on this issue? @Emilance

**Comment by Devemmy01** [comment]
Can I work on this?

**Comment by Emilance** [comment]
Okay  @Rishav1707 , I see you've created a pull request  on this, I will check it out

**Comment by Emilance** [comment]
> Can I work on this?
Thanks for showing interest in contributing @Devemmy01. Kindly turn on notification for the repository,  I  will create some issues that you can contribute  to very soon
